name: Job Scraper Pipeline

on:
  schedule:
    # 00:30 UTC = 07:30 WIB
    - cron: "30 0 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # DOWNLOAD PROXY FROM REPO PROXY-LIST
      - name: Download latest proxy list
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo: mkhafidm/proxy-list
          workflow: update-proxy.yml
          name: proxy-lists
          path: ./proxies/

      # SETUP PYTHON & DEPENDENCIES
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      # CREDENTIALS & RUN
      - name: Write credentials
        run: echo '${{ secrets.GCP_CREDENTIALS }}' > credentials.json

      - name: Run pipeline
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python main.py